# cargo-dist configuration for Ruchy v1.5.0
# The world's first self-hosting MCP-first programming language

[workspace]
members = ["cargo-dist"]

[dist]
# The preferred cargo-dist version
cargo-dist-version = "0.28.0"

# CI backends
ci = ["github"]

# Target platforms - comprehensive coverage
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl", 
    "aarch64-unknown-linux-gnu",
    "aarch64-unknown-linux-musl",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-pc-windows-msvc",
    "aarch64-pc-windows-msvc",
]

# Installers to generate
installers = [
    "shell",      # Unix shell installer
    "powershell", # Windows PowerShell installer  
    "homebrew",   # macOS/Linux Homebrew
    "npm",        # Node.js wrapper
    "msi",        # Windows MSI installer
]

# Archive formats
unix-archive = ".tar.gz"
windows-archive = ".zip"

# Include files in archives
include = [
    "README.md",
    "LICENSE",
    "CHANGELOG.md", 
    "SELF_HOSTING_ACHIEVEMENT.md",
    "examples/**/*",
]

# Auto-generate shell completions
install-generated = ["shell-completions"]

# GitHub Release settings
github-release = true
github-release-notes = "CHANGELOG.md"

# Package metadata
[package]
name = "ruchy"
version = "1.5.0"
description = "The world's first self-hosting MCP-first programming language"
authors = ["Ruchy Contributors"]
license = "MIT"
repository = "https://github.com/paiml/ruchy"
homepage = "https://ruchy-lang.org"
documentation = "https://docs.ruchy-lang.org"
keywords = ["compiler", "self-hosting", "mcp", "language", "transpiler"]
categories = ["development-tools", "compilers"]

# Build settings
[build]
pre-build-command = "cargo build --release"
features = ["self-hosting", "mcp-integration"]