[package]
name = "ruchy-wasm"
collaborators = ["Ruchy Contributors"]
description = "WebAssembly bindings for the Ruchy compiler"
version = "3.3.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/yourorg/ruchy"

[lib]
crate-type = ["cdylib"]

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
strip = true
panic = "abort"